project_id = "kmgmjfifunncweqgnbvz"

[functions.get-paypal-client-id]
verify_jwt = false

[functions.get-paypal-plan-ids]
verify_jwt = false

[functions.generate-paypal-client-token]
verify_jwt = false

[functions.get-payment-client-id]
verify_jwt = false

[functions.get-plan-ids]
verify_jwt = false

[functions.generate-payment-client-token]
verify_jwt = false
