project_id = "kmgmjfifunncweqgnbvz"

[functions.create-whop-checkout]
verify_jwt = false

[functions.whop-webhook]
verify_jwt = false

[functions.verify-whop-access]
verify_jwt = false

[functions.get-shared-proposal]
verify_jwt = false

[functions.send-proposal-email]
verify_jwt = false

[functions.get-subscription-status]
verify_jwt = false

[functions.send-contact-email]
verify_jwt = false

[functions.send-newsletter-email]
verify_jwt = false